### ISSUE TITLE
Print Output as and When it Finishes

### ISSUE THREAD

**Issue by amitsi** [amitsi/pluribus-ansible#200]
If Configuring 100 Vrouter Interfaces......Print JSON output as and when it finished so we can show constant progress rather than waiting for the entire 100 Interface output to be printed after 2 hours

@KyroChi as discussed

**Comment by KyroChi** [comment]
@ashxjain @amitsi 

Here are some helpful links on the subject:
[Simple answer is that we cannot do this.](https://stackoverflow.com/a/25921243/5161833)
[Async operations in Ansible.](https://github.com/ansible/ansible/issues/3887)

Basically, the Ansible dev team doesn't want to do this because on big deployments it bogs down the system. They also feel that this feature is not in compliance with the Ansible architecture.

There is however the async [playbook action](http://docs.ansible.com/ansible/playbooks_async.html), which we may be able to use to alert the user that things are in fact being done and the playbook hasn't hung. 

Let me know if you want me to create an async example to see how you like it. I am disappointed that Ansible does not support a method to do this in the AnsibleModule object ☹️

**Comment by KyroChi** [comment]
Going to see if I can get [this](http://docs.ansible.com/ansible/debug_module.html) to do what we want tomorrow

**Comment by KyroChi** [comment]
@amitsi @ashxjain 

Ansible denounces this kind of behavior, they have had requests to implement such a process which were firmly denied. Even using an async playbook action we will not be able to do this. And we cannot use debug actions to do this either.

There are a few "solutions", although I hesitate to call them that. I have read that some people have had success with dumping output to a file and running the playbook tasks in the background, however this really only works with simple modules, and with the current way we are running the playbooks we don't really want to be doing this. In addition we will have to implement functionality to manage temporary files (which is doable) and make additional calls in every single playbook to use a shell script to cat the files. Ansible doesn't like to execute complex modules async, so this gets really complicated to trick Ansible into thinking that its a simple module. 

The other "solution" is to pipe the stdout through an unused port on the switch and listening to that port with the Ansible host. As you can imagine this is painful at best for one switch, and quickly become complex. To do this in a realistic way we would want to write some sort of program to sit on the Ansible host and read from all of the various inputs and output the stdout from each of the remote switches. This would mean developing a third party application to handle this... which isn't out of the realm of possibility but will take time away from developing modules.

All of these hacks are going to require a great deal of configuration for a deployment, and will likely not work on cross platform deployments.

The other (and best) option is to follow a traditional Ansible module architecture and create the interfaces individually, this will allow for their CLI output to be printed as they are created. For example 100 tasks rather than one big task. We can organize these actions into a specific playbook which can be called from other playbooks rather than handling the logic in python itself.

**Comment by ashxjain** [comment]
@KyroChi ,

Thanks a lot for looking into this !

One solution which even i was thinking was to open a socket on Ansible host (this can be opened using stdout callback plugin) and have a task (module) to connect to that socket and send output data which ansible writes into the file. This task will run on every switch in background (it will start as a parallel task for every playbook). This way we have kept changes in a such a way that we don't do any changes to the other modules. We'll only have to write new playbooks with above additional task.

Obviously one other solution is to make every command a task. But it will be very complicated.
